### ISSUE TITLE
Push notification redirects in app

### ISSUE THREAD

**Issue by jorgtron** [pmusaraj/discourse-mobile-single-site-app#13]
If the user received a push notification while the app is open, there is only an option to select "OK" on the notifcation. When the user taps "OK" he is taken to the URL for the notification. This can be annoying if the user is reading a topic or composing a post, because they can't stop the redirect. Adding another option to the modal could perhaps work, for example having "Show" or "Close" as the options instead of "OK"

**Comment by jorgtron** [comment]
I've seen this happen and when redirected the new post I was writing was lost - very frustrating.

**Comment by pmusaraj** [comment]
Thanks, fixed as of this commit: https://github.com/pmusaraj/discourse-mobile-single-site-app/commit/c98ab1468ffb03030ff9793d17fe43af99d995a6
