### ISSUE TITLE
Can't build since XCode 9.4 (iOS 11.4)

### ISSUE THREAD

**Issue by notstephen** [pmusaraj/discourse-mobile-single-site-app#14]
Failed to load bundle (http://localhost:8081/platform.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module 'DocumentSelectionState' from '/node_modules/react-native/Libraries/Components/TextInput/TextInput.js': Module does not exist in the module map.

**Comment by pmusaraj** [comment]
Pretty sure this is no longer an issue, closing.
