### ISSUE TITLE
Update webview to add swipe to navigate in iOS

### ISSUE THREAD

**Issue by jtbayly** [pmusaraj/discourse-mobile-single-site-app#16]
Below is the new default webview component for React Native. It should support swipe to go back. Looks incredibly easy to drop in as a replacement. I don’t have an app up and running yet though. Maybe one of you that already has an app can try it?
https://github.com/react-native-community/react-native-webview/blob/master/README.md

**Comment by pmusaraj** [comment]
This is now done (as of 5 minutes ago).
