### ISSUE TITLE
How does this connect to the Discourse application?

### ISSUE THREAD

**Issue by osseonews** [pmusaraj/discourse-mobile-single-site-app#17]
I am sorry if this sounds like a basic question, but where in this app is a connection built to discourse installation? I looked in default.variables and there is nowhere to put API info so as to connect to the external Discourse installation to grab the information for the app. How is the app getting the information from the external installation? Other react native apps that I've used have a config file with app key/secret pair to connect to the external application.

**Comment by waffleslop** [comment]
I'm attempting to build the app now and in `app.variables.js` there's a line that says:

global.siteDomain = 'yoursite.com'

That will then display your website, which will show the login screen or whatever your site displays. This is a webkit app, as I understand it. It's just a simple browser for a Discourse website. This app does not work with Discourse's API.
