### ISSUE TITLE
Doesn't play well with LinkedIn oAuth plugin

### ISSUE THREAD

**Issue by nommaz** [pmusaraj/discourse-mobile-single-site-app#3]
Hello

Doesn't play well with LinkedIn oAuth plugin.
Sometimes it works but other times it doesn't. Even when it does work it leaves a Done button on the page which returns the user to login page.

BTW this function works fine on the official generic Discourse iOS app

Pls let me know how to contact you directly to discuss terms for this feature.

**Comment by pmusaraj** [comment]
Recent merge should fix this (tested with Linkedin, Facebook, Patreon). It fails for Google, though.
