### ISSUE TITLE
Connect button not working

### ISSUE THREAD

**Issue by nommaz** [pmusaraj/discourse-mobile-single-site-app#4]
Having several issues with the connect button. First of all it appears blank unless you click on it:

<img width="375" alt="screen shot 2017-10-31 at 10 39 26 am" src="https://user-images.githubusercontent.com/10116478/32212879-e5c70f86-be29-11e7-921e-c045d3b344b4.png">

Can only see it when I click on it.
<img width="374" alt="screen shot 2017-10-31 at 10 48 32 am" src="https://user-images.githubusercontent.com/10116478/32212890-f5260aa4-be29-11e7-98a7-50d309bb7b63.png">

When I click I get the screen below which I understand should eventually lead me to iPhone notification allow screen...

<img width="374" alt="screen shot 2017-10-31 at 10 48 32 am" src="https://user-images.githubusercontent.com/10116478/32213931-4e4ff866-be2e-11e7-8bc7-b8f5442114b7.png">

I just get a blank screen instead. 

<img width="374" alt="screen shot 2017-10-31 at 10 48 32 am" src="https://user-images.githubusercontent.com/10116478/32213934-50877d8e-be2e-11e7-90bf-6e4035deeb79.png">

I need to kill the app to get out of this screen.

**Comment by pmusaraj** [comment]
A few possible reasons:

1) can you check that you aren't using white for both background and text color in the global.js configuration? 

2) The white screen issue sounds like a misconfiguration of the plugin on the server. Did you follow all the steps of the Onesignal Discourse plugin?

**Comment by nommaz** [comment]
1. I didn't make any changes to default colors but will try playing around with them. Maybe related to my custom discourse theme.. 

2. Is there a more direct way to test what the plugin issue might be? (i.e. via browser) 

it looks ok on the surface pls see below images:

<img width="759" alt="screen shot 2017-11-01 at 8 09 07 am" src="https://user-images.githubusercontent.com/10116478/32260954-58f700e4-bedc-11e7-822d-008eb32a99c1.png">

<img width="802" alt="screen shot 2017-11-01 at 8 09 39 am" src="https://user-images.githubusercontent.com/10116478/32260961-60acc2a6-bedc-11e7-8ebe-5508b381886c.png">

**Comment by nommaz** [comment]
solved by adding `discosingle://auth_redirect` to `allowed user api auth redirects` setting

**Comment by pmusaraj** [comment]
Thanks, reopening because readme needs to be updated.
