### ISSUE TITLE
Minor: Connect buttons remains after successful connect

### ISSUE THREAD

**Issue by nommaz** [pmusaraj/discourse-mobile-single-site-app#5]
1. Click skip then login using discourse login button. Click connect after succesful login. Authorize comes up and notifications are allowed. When the site returns after Apple notification prompt, bottom row housing connect button should be hidden

2. Click skip then connect _before_ discourse login and nothing seems to happen (the page refreshes if you pay attention). It gives the impression to the user as if the button is broken, however it does do its job and once user logs in to discourse she sees the authorize page right away. It would be great if the bottom row housing the connect button could be hidden until user is authenticated with discourse.

**Comment by pmusaraj** [comment]
Yeah... maybe. however, the label for that button is configurable in global.js.

**Comment by nommaz** [comment]
I also noticed the below behavior in flow number 2. My site doesnt show any content to non logged in users, this maybe why it is happening.

1. Click skip then login using discourse login button. Click connect after succesful login. Authorize comes up and notifications are allowed. Perfect flow.

2. Click skip then connect before discourse login and nothing seems to happen (the page refreshes if you pay attention). It looks as if the button is broken. But after login it does do its job. So the simplest fix I can think of is to display a message to user such as "You need to login before connecting"

**Comment by nommaz** [comment]
You are right, just wanted to make sure I am not misinterpreting its function. By the way I updated my original comment to reflect 2 different cases

**Comment by pmusaraj** [comment]
This should be now fixed with the recent merge.
