### ISSUE TITLE
Connect prompt still showing up

### ISSUE THREAD

**Issue by mtawil** [pmusaraj/discourse-mobile-single-site-app#8]
Hello,

I thank you for this app, I did install it, and everything is working fine.

There is just one issue I can't resolve it: connect prompt still showing up even after grant permissions.

I attached the video for more explanation.
[DiscourseAppIssue.mp4.zip](https://github.com/pmusaraj/discourse-mobile-single-site-app/files/1672868/DiscourseAppIssue.mp4.zip)

Can you guide me please how this problem can be solved?
Thank you.

**Comment by pmusaraj** [comment]
This could happen for a variety of reasons, but the main reason for it would be that you haven't added https://onesignal.com/api/v1/notifications to Discourse's `allowed user api push urls`. If you have done that, and it's still happening, let me know.

**Comment by mtawil** [comment]
Yes, it works now!

Thank you!
