### ISSUE TITLE
Getting error in build stage after  using react-native-rename

### ISSUE THREAD

**Issue by pesarkhobeee** [pmusaraj/discourse-mobile-single-site-app#9]
Hello
I got this error after that I renamed my app with help of react-native-rename 
```
error: cannot find symbol
            new CustomWebViewPackage(),
                ^
  symbol: class CustomWebViewPackage


```
would you please fix this problem?
![screenshot from 2018-03-10 21-32-29](https://user-images.githubusercontent.com/147461/37246551-6dbd7e42-24ab-11e8-8533-2de328842649.png)

**Comment by pmusaraj** [comment]
Ah, yes, this is because of `CustomWebView` (which fixes file uploads in Android). After renaming the app, you need to manually edit some files in subfolders under `android/app/src/main/java`, and replace `com.discosingle;` at the beginning of every file with your new bundle ID. The rename script does it for `MainActivity.java` and `MainApplication.java`, you need to manually do this for the remaining files. 

Thanks for the request though, I'll update the readme to include this information.

**Comment by pesarkhobeee** [comment]
thank you but as you can see in the picture there is no more file in that directory and even I couldn't find any string with "discosingle" inside the existing files!
![screenshot from 2018-03-11 21-02-05](https://user-images.githubusercontent.com/147461/37257911-c53bdf46-256f-11e8-8ed4-59ed6b4d4648.png)

**Comment by pmusaraj** [comment]
Are you on `master`? Before renaming, do you see the `CustomWebView` files in there? They should be. See this: https://github.com/pmusaraj/discourse-mobile-single-site-app/tree/master/android/app/src/main/java/com/discosingle

**Comment by pesarkhobeee** [comment]
Well, I clone a fresh copy and tried again and I saw same problem! 
It seems that this is a bug:
https://github.com/junedomingo/react-native-rename/issues/47
![screenshot from 2018-03-14 07-39-16](https://user-images.githubusercontent.com/147461/37387407-8740a818-275c-11e8-86bc-197ef9662e93.png)

**Comment by pmusaraj** [comment]
Can you try with an older version of react-native-rename? I’m not on latest and I don’t have this issue.

**Comment by gsanguinetti** [comment]
@pesarkhobeee Have you solve this problem? Have the same issue here...

**Comment by pmusaraj** [comment]
Hmm, odd, I can't reproduce it. See screenshot: 

<img width="1013" alt="screen shot 2018-04-10 at 12 49 03 pm" src="https://user-images.githubusercontent.com/368961/38571147-b6c4f32a-3cbd-11e8-8560-ed8552dee6e1.png">

**Comment by pesarkhobeee** [comment]
@gsanguinett yes!
Actually, before that I use "react-native-rename" command I copied all .java file in a temporary folder and after using that command I just copied missed java files and changed the first line of them by the help of a text editor.

@pmusaraj As I mentioned before this bug already reported:
https://github.com/junedomingo/react-native-rename/issues/47

**Comment by pmusaraj** [comment]
Right, but on 2.2.2, on a Mac I can't reproduce the issue...
